PythonRemoteCZ9/urls.py
from django.contrib import admin
from django.contrib.auth.models import User, Group
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import path

import accounts.views
import base.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', base.views.hello),
    path('', base.views.RoomsView.as_view(), name='rooms'),
    path('room/detail/<pk>/', base.views.room, name='room'),
    path('room/create/', base.views.RoomCreateView.as_view(), name='room_create'),
    path('room/update/<pk>', base.views.RoomUpdateView.as_view(), name='room_update'),
    path('room/delete/<pk>', base.views.RoomDeleteView.as_view(), name='room_delete'),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', PasswordChangeView.as_view(template_name="registration/password_change.html"),
         name='password_change'),
    path('accounts/password_change_done/',
         PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    path('accounts/signup/', accounts.views.SignUpView.as_view(), name='signup'),

    path('search/', base.views.search, name='search')
]

handler403 = 'base.views.handler403'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        instance.groups.add(Group.objects.get(name='Participants'))

accounts/models.py
from django.db import models

# Create your models here.

base/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Model
from django.template.defaultfilters import truncatechars


# Create your models here.
class Room(Model):
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created', 'name']


class Message(Model):
    body = models.TextField()
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def body_short(self):
        return truncatechars(self.body, 50)

    def __str__(self):
        return self.body[0:50]

    class Meta:
        ordering = ['-created', 'body']

base/forms.py
from logging import getLogger

from django import forms
from django.core.exceptions import ValidationError
from django.forms import Form, Textarea, ModelForm

from base.models import Room

LOGGER = getLogger()


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['participants']

    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name) < 2:
            validation_error = "Name must contains min. 2 chars."
            LOGGER.warning(f'{name} : {validation_error}')
            raise ValidationError(validation_error)
        return name.capitalize()

accounts/views.py
from logging import getLogger

from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

LOGGER = getLogger()


# Create your views here.
class SignUpView(CreateView):
    template_name = 'accounts/signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('rooms')

    def form_valid(self, form):
        result = super().form_valid(form)
        cleaned_data = form.cleaned_data
        username = cleaned_data['username']
        password = cleaned_data['password1']
        new_user = authenticate(username=username, password=password)
        if new_user is not None:
            login(self.request, new_user)
        return result

base/views.py
from logging import getLogger

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, FormView, CreateView, UpdateView, DeleteView

from base.forms import RoomForm
from base.models import Room, Message

LOGGER = getLogger()


# Create your views here.
def hello(request):
    s = request.GET.get('s', '')
    return HttpResponse(f'Ahoj {s}!!!')


@login_required
@permission_required(['base.view_room'])
def search(request):
    q = request.GET.get('q', '')
    rooms = Room.objects.filter(
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )
    context = {'object_list': rooms}
    return render(request, 'base/rooms.html', context)


# def rooms(request):
#     rooms = Room.objects.all()
#     context = {'rooms': rooms}
#     return render(request, template_name='base/rooms.html', context=context)


class RoomsView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    template_name = 'base/rooms.html'
    model = Room
    permission_required = 'base.view_room'


@login_required
@permission_required(['base.view_room', 'base.view_message'])
def room(request, pk):
    LOGGER.warning(request.method)
    room = Room.objects.get(id=pk)

    # POST
    if request.method == 'POST':
        if request.user.has_perm('base.add_message'):
            Message.objects.create(
                user=request.user,
                room=room,
                body=request.POST.get('body')
            )
            room.participants.add(request.user)
            room.save()
        return redirect('room', pk=pk)

    # GET
    messages = room.message_set.all()
    context = {'messages': messages, 'room': room}
    return render(request, template_name='base/room.html', context=context)


class RoomCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    template_name = 'base/room_form.html'
    extra_context = {'title': 'CREATE !!!'}
    form_class = RoomForm
    success_url = reverse_lazy('rooms')
    permission_required = 'base.add_room'

    def form_valid(self, form):
        result = super().form_valid(form)
        LOGGER.warning(form.cleaned_data)
        return result


class RoomUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name = 'base/room_form.html'
    extra_context = {'title': 'UPDATE !!!'}
    form_class = RoomForm
    success_url = reverse_lazy('rooms')
    model = Room
    permission_required = 'base.change_room'


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class RoomDeleteView(StaffRequiredMixin, PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    template_name = 'base/room_confirm_delete.html'
    model = Room
    success_url = reverse_lazy('rooms')
    permission_required = 'base.delete_room'


def handler403(request, exception):
    return render(request, '403.html', status=404)

accounts/templates/accounts/signup.html
{% extends 'main.html' %}

{% block content %}
    <h1>Signup</h1>
    <div class="box">
        <form method="POST">
            {% csrf_token %}
            <table>{{ form.as_table }}</table>
            <button type="submit">Signup</button>
        </form>
    </div>
{% endblock %}

base/templates/base/room.html
{% extends 'main.html' %}

{% block content %}
    <h1>{{ room.name }}</h1>
    <div class="box">{{ room.description }}</div>
    <div class="box room__message">
        {% if perms.base.add_message %}
            <form method="POST">
                {% csrf_token %}
                <input name="body" placeholder="Write your message here..."/>
            </form>
        {% endif %}
    </div>
    {% for message in messages %}
        <div class="box">
            {% if user == message.user %}
                <div style="float: right"><b>{{ message.user }}</b> <i>[{{ message.created }}]</i></div>
                <div class="message" style="float: right; background-color: #e16060; color: white;">{{ message.body }}</div>
            {% else %}
                <div><b>{{ message.user }}</b> <i>[{{ message.created }}]</i></div>
                <div class="message">{{ message.body }}</div>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}

base/templates/base/room_confirm_delete.html
{% extends 'main.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class="box">
            <p>Are you sure you want to delete room "{{ object.name }}"?</p>
            <button type="submit">YES</button>
            <a href="{% url 'rooms' %}">Cancel</a>
        </div>
    </form>
{% endblock %}

base/templates/base/room_form.html
{% extends 'main.html'%}

{% block content %}
    <h3>{{ title }}</h3>
    <form method="post">
        {% csrf_token %}
        <div class="box">
            <label for="{{ form.name.id_for_label }}">Room name:</label>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
        <div class="box">
            <label for="{{ form.description.id_for_label }}" style="vertical-align: top">Description:</label>
            {{ form.description }}
            {{ form.description.errors }}
        </div>
        <button type="submit">Submit</button>
        {{ form.non_field_errors }}
    </form>
{% endblock %}

base/templates/base/rooms.html
{% extends 'main.html' %}

{% block content %}
    <h1>Rooms</h1>
    <div class="box"></div>
    {% for room in object_list %}
        <div class="box">
            <div style="float: left;">
                <a href="{% url 'room' room.id %}">{{ room.name|capfirst }}</a><br/>
                {{ room.description }}
            </div>
            <div style="float: right;">
                {% if perms.base.change_room %}
                    <a href="{% url 'room_update' room.id %}">Edit</a>
                {% endif %}
                {% if perms.base.delete_room and perms.base.delete_message and user.is_staff %}
                    <a href="{% url 'room_delete' room.id %}">Delete</a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="http://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" type="text/css"/>
    <link href="http://fonts.googleapis.com/css?family=Bevan" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}"/>
    <title>Title</title>
</head>
<body>
<div id="wrapper">
    <div id="header">
        <div id="logo">
            <h1>Chatterbox</h1>
        </div>
        {% if user.is_authenticated %}
            <div id="search">
                <form action="{% url 'search' %}" method="get">
                    <div>
                        <input class="text" name="q" size="32" maxlength="64">
                    </div>
                </form>
            </div>
            <div id="menu">
                {% include 'navbar.html' %}
            </div>
        {% endif %}
    </div>
    <div id="page">
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <br class="clearfix">
    </div>
    <br class="clearfix">
</div>
</body>
</html>

templates/navbar.html
<ul>
    {% if user.is_authenticated %}
        <li class="first active">
            <a href="{% url 'rooms' %}">Rooms</a>
        </li>

        {% if perms.base.add_room %}
            <li>
                <a href="{% url 'room_create' %}">Create room</a>
            </li>
        {% endif %}


        <li class="last-child">
            {{ user.username }}
        </li>
        <li class="last-child">
            <a href="{% url 'password_change' %}">Password change</a>
        </li>
        <li class="last-child">
            <a href="{% url 'logout' %}">Logout</a>
        </li>
    {% else %}
        <li class="last-child">
            <a href="{% url 'login' %}">Login</a>
        </li>
    {% endif %}

</ul><br class="clearfix"/>